[test]
# Exclude tmp directory and playwright spec files from unit tests
exclude = ["**/tmp/**", "**/*.spec.ts", "**/*.spec.js", "**/test/**/*.spec.ts", "**/tests/**/*.spec.ts", "**/tests/**/*.spec.js", "packages/demo/test/**"]

# Coverage is disabled by default, use --coverage flag to enable
coverage = false

# Set low thresholds for now (10%)
coverageThreshold = { lines = 0.1, functions = 0.1, statements = 0.1, branches = 0.1 }

# Skip coverage for demo package
coverageSkipTestFiles = true