[test]
# Exclude tmp directory and playwright spec files from unit tests  
exclude = [
  "tmp/**", 
  "packages/demo/**", 
  "**/e2e/**",
  "**/*.spec.ts", 
  "**/*.spec.js",
  "**/test/**/*.spec.ts",
  "**/test/**/*.spec.js"
]

# Coverage is disabled by default, use --coverage flag to enable
coverage = false

# No thresholds at root level - each package sets its own
# coverageThreshold = { lines = 0.1, functions = 0.1, statements = 0.1, branches = 0.1 }

# Skip coverage for demo package
coverageSkipTestFiles = true