[test]
# Coverage is enabled for --coverage flag and test:coverage script
coverage = true
# Pandapage package: 47.44% functions, 38.84% lines (lowest coverage - needs improvement)
# TODO: Re-enable when bun fixes coverage threshold feature
# coverageThreshold = 35

# Exclude test files and types from coverage
coverageSkipTestFiles = true
exclude = ["**/*.spec.ts", "**/*.test.ts", "test/**", "tmp/**"]