[test]
# Coverage is disabled by default, use --coverage flag to enable
coverage = false

# Set low thresholds for now (10%)
coverageThreshold = { lines = 0.1, functions = 0.1, statements = 0.1, branches = 0.1 }

# Exclude test files and types from coverage
coverageSkipTestFiles = true
exclude = ["**/*.spec.ts", "**/*.test.ts", "test/**"]