[test]
# Coverage is enabled for --coverage flag and test:coverage script
coverage = true
# Pandapage package: Updated to 73.79% functions, 64.04% lines after adding validation tests
coverageThreshold = { line = 60, function = 70, statement = 55, branch = 45 }

# Exclude test files and types from coverage
coverageSkipTestFiles = true
exclude = ["**/*.spec.ts", "**/*.test.ts", "test/**", "tmp/**"]