[test]
# Coverage is enabled for --coverage flag and test:coverage script
coverage = true
# Pandapage package: Updated to 69.72% functions, 59.54% lines after adding document parser tests
coverageThreshold = { line = 55, function = 65, statement = 50, branch = 40 }

# Exclude test files and types from coverage
coverageSkipTestFiles = true
exclude = ["**/*.spec.ts", "**/*.test.ts", "test/**", "tmp/**"]