[test]
# Enable coverage with realistic thresholds
coverage = true

# Start with achievable thresholds and increase over time
coverageThreshold = { lines = 0.38, functions = 0.47, statements = 0.38, branches = 0.20 }

# Exclude test files and types from coverage
coverageSkipTestFiles = true
exclude = ["**/*.spec.ts", "**/*.test.ts", "test/**"]