[test]
# Coverage is enabled for --coverage flag and test:coverage script
coverage = true

# Coverage enabled without thresholds - debugging threshold issues
# coverageThreshold = { lines = 0.01, functions = 0.01, statements = 0.01, branches = 0.01 }

# Exclude test files and types from coverage
coverageSkipTestFiles = true
exclude = ["**/*.spec.ts", "**/*.test.ts", "test/**", "tmp/**"]