[test]
# Enable coverage reporting with thresholds
# Renderer Markdown package: 82.35% functions, 72.32% lines
coverage = true
coverageThreshold = { line = 72, function = 82, statement = 70, branch = 60 }
coverageSkipTestFiles = true
