[test]
# Enable coverage reporting - thresholds disabled due to bun bug
# Renderer Markdown package: 82.35% functions, 72.32% lines
coverage = true
# coverageThreshold = { lines = 70, functions = 80 }
coverageSkipTestFiles = true
