[test]
# Enable coverage reporting with thresholds
# Renderer Markdown package: 82.35% functions, 72.32% lines
coverage = true
# TODO: Re-enable when bun fixes coverage threshold feature
# coverageThreshold = 70
coverageSkipTestFiles = true
