[test]
# Enable coverage for renderer-markdown package
coverage = true

# Realistic thresholds based on current coverage  
coverageThreshold = { lines = 0.95, functions = 0.95, statements = 0.95, branches = 0.5 }

# Exclude test files from coverage
coverageSkipTestFiles = true