[test]
# Enable coverage for parser package
coverage = true


# Coverage thresholds disabled due to bun test runner bug
# Even with thresholds below actual coverage, bun coverage still fails  
# Current actual coverage: 73.26% functions, 84.70% lines
# TODO: Re-enable when bun fixes coverage threshold calculation
# coverageThreshold = { lines = 80, functions = 70 }

# Exclude test files and dist directory from coverage
coverageSkipTestFiles = true