[test]
# Enable coverage for parser package
coverage = true

# Realistic thresholds based on current coverage
coverageThreshold = { lines = 0.95, functions = 0.75, statements = 0.95, branches = 0.5 }

# Exclude test files from coverage
coverageSkipTestFiles = true