[test]
# Disable coverage for now to fix CI
coverage = false

# Coverage thresholds - currently at 85.76% lines, 73.26% functions
# TODO: Enable coverage and increase thresholds as we improve test coverage
# coverageThreshold = { lines = 0.85, functions = 0.70, statements = 0.85, branches = 0.50 }

# Exclude test files from coverage
coverageSkipTestFiles = true