[test]
# Enable coverage for parser package
coverage = true


# Coverage thresholds - set to actual source file coverage levels
# Coverage thresholds set low to start, can be increased gradually
coverageThreshold = { lines = 0.01, functions = 0.01, statements = 0.01, branches = 0.01 }

# Exclude test files and dist directory from coverage
coverageSkipTestFiles = true