[test]
# Enable coverage for parser package
coverage = true
# Current actual coverage: 73.26% functions, 84.70% lines
coverageThreshold = { line = 84, function = 73, statement = 80, branch = 60 }

# Exclude test files and dist directory from coverage
coverageSkipTestFiles = true

# Load test setup file
preload = ["./src/test-setup.ts"]