[test]
# Enable coverage reporting - thresholds disabled due to bun bug
# Renderer DOM package: 78.57% functions, 77.05% lines  
coverage = true
# coverageThreshold = { lines = 75, functions = 75 }
coverageSkipTestFiles = true
