[test]
# Enable coverage reporting with thresholds
# Renderer DOM package: 78.57% functions, 77.05% lines  
coverage = true
# TODO: Re-enable when bun fixes coverage threshold feature
# coverageThreshold = 75
coverageSkipTestFiles = true
