name: CI (Parallel)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '.gitignore'
      - 'LICENSE'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '.gitignore'
      - 'LICENSE'

jobs:
  # Run linting and formatting checks in parallel
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install --frozen-lockfile
      
    - name: Run Biome lint
      run: bun run lint
      
    - name: Check file sizes
      run: bun run check-file-sizes

  # Run TypeScript checks in parallel
  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install --frozen-lockfile
      
    - name: Build all packages
      run: bun run build
      
    - name: TypeScript check
      run: bun run typecheck

  # Run unit tests in parallel
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install --frozen-lockfile
      
    - name: Build all packages
      run: bun run build
      
    - name: Run unit tests with coverage
      run: bun run test:unit

  # Run E2E tests (only after all other checks pass)
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [lint, typecheck, unit-tests]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install --frozen-lockfile
      
    - name: Install Playwright browsers
      run: cd packages/viewer && bunx playwright install --with-deps
      
    - name: Build viewer app
      run: cd packages/viewer && bun run build
      
    - name: Run E2E tests
      run: cd packages/viewer && bun run test:e2e
      
    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report
        path: packages/viewer/playwright-report/
        retention-days: 30

  # Final check that all jobs passed
  all-checks-passed:
    name: All Checks Passed
    runs-on: ubuntu-latest
    needs: [lint, typecheck, unit-tests, e2e-tests]
    steps:
    - name: All checks passed
      run: echo "All CI checks have passed successfully!"