name: Documentation Check

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '**/*.md'

jobs:
  docs-check:
    name: Documentation Updated
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Documentation changes detected
      run: |
        echo "✅ Documentation changes detected"
        echo "Skipping CI/CD pipeline - no code changes to test or deploy"