name: Post-merge Build

on:
  push:
    branches: [ main ]
    paths:
      - 'pdf-parser/**'
      - '.github/workflows/post-merge.yml'

jobs:
  build-test-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install MoonBit
      run: |
        curl -fsSL https://www.moonbitlang.com/install/unix.sh | bash
        echo "$HOME/.moon/bin" >> $GITHUB_PATH
    
    - name: Verify MoonBit installation
      run: moon version
    
    - name: Build PDF parser
      working-directory: ./pdf-parser
      run: |
        moon build --target wasm-gc
        moon build --target js
    
    - name: Run tests
      working-directory: ./pdf-parser
      run: moon test
    
    - name: Copy WASM artifact to root
      run: cp pdf-parser/target/wasm-gc/release/build/main/main.wasm pdf-parser.wasm
    
    - name: Upload WASM artifact
      uses: actions/upload-artifact@v4
      with:
        name: pdf-parser-wasm
        path: pdf-parser.wasm
    
    - name: Upload JS artifact
      uses: actions/upload-artifact@v4
      with:
        name: pdf-parser-js
        path: pdf-parser/target/js/release/build/main/main.js
    
    - name: Create release tag (optional)
      if: contains(github.event.head_commit.message, '[release]')
      run: |
        VERSION=$(date +%Y%m%d-%H%M%S)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        git tag "v$VERSION"
        git push origin "v$VERSION"
    
    - name: Create GitHub Release (optional)
      if: contains(github.event.head_commit.message, '[release]')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.VERSION }}
        files: |
          pdf-parser.wasm
          pdf-parser/target/js/release/build/main/main.js
        body: |
          Automated release from commit ${{ github.sha }}
          
          ## Changes
          ${{ github.event.head_commit.message }}
          
          ## Artifacts
          - `pdf-parser.wasm` - WebAssembly module
          - `main.js` - JavaScript module