name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
    
    - name: Build packages
      run: bun run build
      working-directory: packages/pandapage
    
    - name: Run unit tests (deterministic only)
      run: bun run test:ci
      working-directory: packages/pandapage
    
    - name: Run E2E tests
      run: |
        bun playwright install --with-deps
        bun run test:e2e
      working-directory: packages/demo
      
  test-multiple-os:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
    
    - name: Build packages
      run: bun run build
      working-directory: packages/pandapage
    
    - name: Run unit tests (deterministic only)
      run: bun run test:ci
      working-directory: packages/pandapage